name: inspectw_camera
description: App de cámara (fotos + descripciones) con proyectos/ubicaciones y exportación ZIP
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  flutter_typeahead: ^5.2.0
  archive: ^3.6.1
  share_plus: ^10.0.2
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.4.0
  image: ^4.1.7        # para el recorte sin deformar
  media_store_plus: 0.1.3  # para guardar en galería (Android)
  path: ^1.8.0 # para manipular rutas de archivos 
  device_info_plus: ^11.5.0 # para detectar si es Android 10+ y usar DCIM
  diacritic: ^0.1.4
  speech_to_text: ^7.3.0
  http: ^0.13.5
  http_parser: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
